In [19]:
# special IPython command to prepare the notebook for matplotlib
%matplotlib inline 

#Array processing
import numpy as np
#Data analysis, wrangling and common exploratory operations
import pandas as pd
from pandas import Series, DataFrame
from sklearn.neighbors import KNeighborsClassifier    
#For visualization. Matplotlib for basic viz and seaborn for more stylish figures + statistical figures not in MPL.
import matplotlib.pyplot as plt
import seaborn as sns

#For some of the date operations
import datetime
from sklearn.neighbors import KNeighborsClassifier 
from sklearn import metrics

from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor 
from sklearn.svm import SVC
from sklearn.linear_model import  LogisticRegression, LinearRegression 
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB

In [20]:
fec_all = pd.read_csv('178329925_T_ONTIME.csv',usecols=['ORIGIN_AIRPORT_ID','DEST_AIRPORT_ID','DEP_TIME','CRS_DEP_TIME','CRS_ARR_TIME'],low_memory=False)
lables = pd.read_csv('178329925_T_ONTIME.csv',usecols=['ARR_DEL15'])
replace = fec_all.fillna(0)
lables = lables.fillna(0)

In [21]:
traing_data = replace[:150000]
traing_labels = lables[:150000]
test_data  = replace[150000:]
test_labels =np.array(lables[150000:])

In [22]:
traing_data

,ORIGIN_AIRPORT_ID,DEST_AIRPORT_ID,CRS_DEP_TIME,DEP_TIME,CRS_ARR_TIME
0,12478,12892,900,855,1230
1,12478,12892,900,850,1230
2,12478,12892,900,853,1230
3,12478,12892,900,853,1230
4,12478,12892,900,853,1230
5,12478,12892,900,856,1235
6,12478,12892,900,859,1235
7,12478,12892,900,856,1235
8,12478,12892,900,901,1235
9,12478,12892,900,903,1235
10,12478,12892,900,854,1235
11,12478,12892,900,853,1235
12,12478,12892,900,854,1235
13,12478,12892,900,856,1235
14,12478,12892,900,852,1235
15,12478,12892,900,900,1235
16,12478,12892,900,852,1235
17,12478,12892,900,916,1235
18,12478,12892,900,854,1235
19,12478,12892,900,853,1235
20,12478,12892,900,853,1235
21,12478,12892,900,852,1235
22,12478,12892,900,854,1235
23,12478,12892,900,1043,1235
24,12478,12892,900,903,1235
25,12478,12892,900,854,1235
26,12478,12892,900,0,1235
27,12478,12892,900,0,1235
28,12478,12892,900,855,1235
29,12478,12892,900,858,1235
...,...,...,...,...,...
149970,10397,10874,2050,2049,2233
149971,10397,15304,831,826,953
149972,15304,10397,1045,1037,1219
149973,13204,13487,800,758,1033
149974,10397,15370,942,942,1055
149975,15370,10397,1130,1126,1418
149976,11697,11433,1601,1601,1905
149977,12892,13495,820,819,1405
149978,14635,11433,1137,1124,1431
149979,11433,13303,1200,1159,1510
149980,10397,12889,1910,1910,2050
149981,12892,11193,1215,1205,1923
149982,10721,11433,900,912,1123
149983,12953,13204,1855,1853,2207
149984,10397,13198,1955,1947,2110
149985,13577,10397,650,644,818
149986,11697,10397,1145,1142,1348
149987,11057,10397,745,742,910
149988,14679,10397,645,645,1349
149989,10397,15370,2034,2031,2148
149990,14843,10397,1640,1629,1944
149991,13487,12953,1946,1944,2323
149992,14100,13487,1650,1712,1854
149993,10721,10397,820,820,1127
149994,12889,10397,600,629,1247
149995,11433,11697,1525,1525,1835
149996,11697,11433,1131,1127,1442
149997,10713,13487,630,625,1024
149998,13487,11292,1530,1533,1640
149999,11292,11433,600,600,1105

In [23]:
test_data

,ORIGIN_AIRPORT_ID,DEST_AIRPORT_ID,CRS_DEP_TIME,DEP_TIME,CRS_ARR_TIME
150000,11433,11292,841,839,1007
150001,10397,13930,1345,1346,1450
150002,12992,10397,710,707,949
150003,11292,10397,800,755,1305
150004,10397,12191,1259,1256,1421
150005,12191,10397,1517,1514,1814
150006,13204,10397,720,715,905
150007,13871,13487,645,654,804
150008,11433,15304,1525,1519,1810
150009,13487,14100,1946,1950,2317
150010,10821,10397,615,613,820
150011,10397,11697,1510,1509,1704
150012,11697,10397,1810,1804,2013
150013,10397,11697,845,843,1039
150014,10397,14683,2040,2039,2226
150015,14869,12892,1648,1729,1745
150016,11433,14679,2000,2008,2207
150017,10397,11278,1940,1938,2123
150018,11278,10397,1300,1253,1501
150019,10397,14683,825,824,1014
150020,11637,13487,702,657,823
150021,11433,11292,1226,1216,1357
150022,14107,10397,45,36,606
150023,12953,10397,800,757,1048
150024,13232,10397,1205,1159,1501
150025,12889,10397,1400,1357,2050
150026,11433,13487,835,831,949
150027,12892,10397,1335,1334,2044
150028,10397,12892,1233,1251,1440
150029,14869,10397,710,705,1250
...,...,...,...,...,...
469938,13930,14635,909,906,1306
469939,12892,12758,1003,1114,1402
469940,11042,12266,550,550,805
469941,13930,12892,1305,1322,1535
469942,14100,13930,940,937,1108
469943,11618,14635,2005,2003,2309
469944,11618,12266,1630,1724,1926
469945,15304,11618,1018,1016,1259
469946,11618,13303,1025,1033,1339
469947,12892,12266,1635,1637,2147
469948,12266,13930,920,924,1159
469949,12266,13495,1953,2001,2103
469950,12266,11292,1543,1703,1721
469951,14908,12266,849,848,1357
469952,13930,12266,515,514,810
469953,11042,12266,1742,1737,1959
469954,15304,11042,1125,1121,1356
469955,11618,13204,2025,2058,2320
469956,10713,11292,1406,1411,1601
469957,10821,12266,1748,1823,2025
469958,11292,10821,957,1011,1513
469959,13930,13871,1514,1527,1647
469960,11697,12266,840,843,1033
469961,12266,14107,1134,1133,1340
469962,11618,14635,1510,1508,1822
469963,14027,11618,1003,956,1249
469964,14771,14057,843,842,1032
469965,14683,12266,815,813,917
469966,11618,14771,1816,1856,2150
469967,14771,12264,2312,2307,725

In [24]:
  
cart_model_default = DecisionTreeClassifier(random_state = 1234, criterion = "entropy") 
cart_model_default.fit(traing_data,traing_labels)
print(cart_model_default) 
predictions_dtree_default = cart_model_default.predict(test_data)
print (metrics.accuracy_score(test_labels,predictions_dtree_default) )

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            random_state=1234, splitter='best')
0.858929642964

In [25]:
nb_gaussian_model = GaussianNB() #create the model
nb_gaussian_model.fit(traing_data,traing_labels)
print(nb_gaussian_model) 
predictions_gaussian_nb = nb_gaussian_model.predict(test_data) #make the predictions
print (metrics.accuracy_score(test_labels,predictions_gaussian_nb) )

GaussianNB()
0.783125187519

F:\Downloads\WinPython-32bit-3.4.3.4\python-3.4.3\lib\site-packages\sklearn\utils\validation.py:449: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [15]:
lr_model_default = LogisticRegression(random_state = 1234)      
lr_model_default.fit(traing_data, traing_labels)
predictions_lr_model_default = lr_model_default.predict(test_data)
print(metrics.accuracy_score(test_labels,predictions_lr_model_default))

0.832461371137

F:\Downloads\WinPython-32bit-3.4.3.4\python-3.4.3\lib\site-packages\sklearn\utils\validation.py:449: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [18]:
rf_model_default = RandomForestClassifier(random_state = 1234)                                                                    
rf_model_default.fit(traing_data, traing_labels)                                                                    
print(rf_model_default)            
predictions_rf_default = rf_model_default.predict(test_data)
print (metrics.accuracy_score(test_labels,predictions_rf_default) )

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=1234, verbose=0,
            warm_start=False)
0.901327632763

F:\Downloads\WinPython-32bit-3.4.3.4\python-3.4.3\lib\site-packages\IPython\kernel\__main__.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  from IPython.kernel.zmq import kernelapp as app